In [3]:
import numpy as np
import pandas as pd
x = 1
np.arange(2, 100, 3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50,
       53, 56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

In [4]:
np.arange(1, 3)
print(x)

1


In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones(2)

array([1., 1.])

In [8]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.linspace(0, 99, 10)

array([ 0., 11., 22., 33., 44., 55., 66., 77., 88., 99.])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.random.rand(4, 3)

array([[0.95575139, 0.16114878, 0.674343  ],
       [0.33381566, 0.15586786, 0.86543149],
       [0.28444089, 0.87907055, 0.80550965],
       [0.89029206, 0.51716854, 0.08024752]])

In [12]:
np.random.randn(3)

array([-0.04319824, -1.32392797,  0.22025333])

In [13]:
np.random.randint(3, 1000, 100)

array([183, 876, 512, 338, 932, 958,  36,  83, 905, 438, 333,  62, 260,
       667, 651, 641, 646, 935, 323, 278, 420, 294, 205, 513, 256,  78,
       291, 557, 821, 613, 844, 296, 766, 187, 947, 502, 304, 290, 941,
       216, 852, 764, 371, 433, 845, 981, 292,  73, 420, 904,  82, 822,
       571, 114, 671, 125, 172, 167, 587, 919, 661, 805, 311, 126, 375,
       601, 746, 724, 483, 605, 372,  59, 431, 147,  86, 689, 408, 263,
        12, 806, 128,  79, 895, 387, 375, 217, 248, 695,  73, 645, 546,
       314, 674, 796, 438, 232, 839,  84, 176,  93])

In [14]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [15]:
arr = np.arange(0, 25)
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
random_arr = np.random.randint(0, 101, 10)
random_arr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [17]:
random_arr.max()


99

In [18]:
random_arr.min()

2

In [19]:
random_arr.argmax()

5

In [20]:
random_arr.argmin()

7

In [21]:
random_arr.dtype

dtype('int32')

In [22]:
arr.shape

(25,)

In [23]:
arr = arr.reshape((5, 5))

In [24]:
arr.shape

(5, 5)

In [25]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [26]:
arr = np.arange(0, 11)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [29]:
arr[1:5] = 0
arr

array([ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10])

In [30]:
arr_2d = np.arange(0, 9)
arr_2d = arr_2d.reshape(3, 3)

In [31]:
arr_2d[0]

array([0, 1, 2])

In [32]:
arr_2d[-1]

array([6, 7, 8])

In [33]:
arr_2d.shape

(3, 3)

In [34]:
arr_2d[0, 0]

0

In [35]:
arr_2d[:2, 1:]

array([[1, 2],
       [4, 5]])

In [36]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [38]:
bool_arr = arr > 4

In [39]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [40]:
arr = np.arange(0, 10)
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [42]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
arr = np.arange(0, 25)
arr = arr.reshape(5, 5)

In [44]:
arr.shape

(5, 5)

In [45]:
arr.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [46]:
df = pd.read_csv(r'C:\Users\Home\PycharmProjects\UDEMY_ML_NEW\data\tips.csv')
df

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  
243     Michelle Hardin  3511451626698139    Thur672  

[244 rows x 11 columns]

In [47]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [48]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [49]:
df.head(10)

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   
5       25.29  4.71    Male     No  Sun  Dinner     4              6.32   
6        8.77  2.00    Male     No  Sun  Dinner     2              4.38   
7       26.88  3.12    Male     No  Sun  Dinner     4              6.72   
8       15.04  1.96    Male     No  Sun  Dinner     2              7.52   
9       14.78  3.23    Male     No  Sun  Dinner     2              7.39   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251  
5          Erik Smith   213140353657882    Sun9679  
6  Kristopher Johnson  2223727524230344    Sun5985  
7         Robert Buck  3514785077705092    Sun8157  
8     Joseph Mcdonald  3522866365840377    Sun6820  
9       Jerome Abbott  3532124519049786    Sun3775

In [50]:
df.tail(1)

total_bill  tip     sex smoker   day    time  size  price_per_person  \
243       18.78  3.0  Female     No  Thur  Dinner     2              9.39   

          Payer Name         CC Number Payment ID  
243  Michelle Hardin  3511451626698139    Thur672

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object 
 3   smoker            244 non-null    object 
 4   day               244 non-null    object 
 5   time              244 non-null    object 
 6   size              244 non-null    int64  
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object 
 9   CC Number         244 non-null    int64  
 10  Payment ID        244 non-null    object 
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB


In [52]:
df.describe()

total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [53]:
df['total_bill']

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...  
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [54]:
my_cols = ['total_bill', 'tip']
df[my_cols]

total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [55]:
df['tip_pecrentage'] = df['tip'] / df['total_bill'] * 100
np.round(df['tip_pecrentage'], 2)

df = df.drop('tip_pecrentage', axis=1)
df.head(1)

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959

In [56]:
df.shape

(244, 11)

In [57]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [58]:
df = df.set_index('Payment ID')

In [59]:
df.head(2)

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun2959          16.99  1.01  Female     No  Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   

            price_per_person          Payer Name         CC Number  
Payment ID                                                          
Sun2959                 8.49  Christy Cunningham  3560325168603410  
Sun4608                 3.45      Douglas Tucker  4478071379779230

In [60]:
df = df.reset_index()

In [61]:
df.head()

Payment ID  total_bill   tip     sex smoker  day    time  size  \
0    Sun2959       16.99  1.01  Female     No  Sun  Dinner     2   
1    Sun4608       10.34  1.66    Male     No  Sun  Dinner     3   
2    Sun4458       21.01  3.50    Male     No  Sun  Dinner     3   
3    Sun5260       23.68  3.31    Male     No  Sun  Dinner     2   
4    Sun2251       24.59  3.61  Female     No  Sun  Dinner     4   

   price_per_person          Payer Name         CC Number  
0              8.49  Christy Cunningham  3560325168603410  
1              3.45      Douglas Tucker  4478071379779230  
2              7.00      Travis Walters  6011812112971322  
3             11.84    Nathaniel Harris  4676137647685994  
4              6.15        Tonya Carter  4832732618637221

In [62]:
df = df.set_index('Payment ID')

In [63]:
df.iloc[0]

total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number             3560325168603410
Name: Sun2959, dtype: object

In [64]:
df.loc[['Sun2959', 'Sun5260']]

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun2959          16.99  1.01  Female     No  Sun  Dinner     2   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   

            price_per_person          Payer Name         CC Number  
Payment ID                                                          
Sun2959                 8.49  Christy Cunningham  3560325168603410  
Sun5260                11.84    Nathaniel Harris  4676137647685994

In [65]:
df = df.drop('Sun2959',axis=0)

In [66]:
one_row = df.iloc[0]
df.append(one_row)

total_bill   tip     sex smoker   day    time  size  \
Payment ID                                                        
Sun4608          10.34  1.66    Male     No   Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No   Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No   Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No   Sun  Dinner     4   
Sun9679          25.29  4.71    Male     No   Sun  Dinner     4   
...                ...   ...     ...    ...   ...     ...   ...   
Sat1766          27.18  2.00  Female    Yes   Sat  Dinner     2   
Sat3880          22.67  2.00    Male    Yes   Sat  Dinner     2   
Sat17            17.82  1.75    Male     No   Sat  Dinner     2   
Thur672          18.78  3.00  Female     No  Thur  Dinner     2   
Sun4608          10.34  1.66    Male     No   Sun  Dinner     3   

            price_per_person        Payer Name         CC Number  
Payment ID                                                        
Sun4608                 3.45    Douglas Tucker  4478071379779230  
Sun4458                 7.00    Travis Walters  6011812112971322  
Sun5260                11.84  Nathaniel Harris  4676137647685994  
Sun2251                 6.15      Tonya Carter  4832732618637221  
Sun9679                 6.32        Erik Smith   213140353657882  
...                      ...               ...               ...  
Sat1766                13.59    Monica Sanders  3506806155565404  
Sat3880                11.34        Keith Wong  6011891618747196  
Sat17                   8.91      Dennis Dixon     4375220550950  
Thur672                 9.39   Michelle Hardin  3511451626698139  
Sun4608                 3.45    Douglas Tucker  4478071379779230  

[244 rows x 10 columns]

In [67]:
df = pd.read_csv(r"C:\Users\Home\PycharmProjects\UDEMY_ML_NEW\data\tips.csv")

In [68]:
bool_series = df['sex'] == 'Male'

In [69]:
df[bool_series]

total_bill   tip   sex smoker  day    time  size  price_per_person  \
1         10.34  1.66  Male     No  Sun  Dinner     3              3.45   
2         21.01  3.50  Male     No  Sun  Dinner     3              7.00   
3         23.68  3.31  Male     No  Sun  Dinner     2             11.84   
5         25.29  4.71  Male     No  Sun  Dinner     4              6.32   
6          8.77  2.00  Male     No  Sun  Dinner     2              4.38   
..          ...   ...   ...    ...  ...     ...   ...               ...   
236       12.60  1.00  Male    Yes  Sat  Dinner     2              6.30   
237       32.83  1.17  Male    Yes  Sat  Dinner     2             16.42   
239       29.03  5.92  Male     No  Sat  Dinner     3              9.68   
241       22.67  2.00  Male    Yes  Sat  Dinner     2             11.34   
242       17.82  1.75  Male     No  Sat  Dinner     2              8.91   

             Payer Name         CC Number Payment ID  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
5            Erik Smith   213140353657882    Sun9679  
6    Kristopher Johnson  2223727524230344    Sun5985  
..                  ...               ...        ...  
236       Matthew Myers  3543676378973965    Sat5032  
237        Thomas Brown  4284722681265508    Sat2929  
239       Michael Avila  5296068606052842    Sat2657  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  

[157 rows x 11 columns]

In [70]:
df[(df['total_bill'] > 20) | (df['sex'] == 'Female')]

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
5         25.29  4.71    Male     No   Sun  Dinner     4              6.32   
..          ...   ...     ...    ...   ...     ...   ...               ...   
238       35.83  4.67  Female     No   Sat  Dinner     3             11.94   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
5            Erik Smith   213140353657882    Sun9679  
..                  ...               ...        ...  
238      Kimberly Crane      676184013727    Sat9777  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
243     Michelle Hardin  3511451626698139    Thur672  

[157 rows x 11 columns]

In [71]:
df[df['day'].isin(['Sat', 'Sun'])]

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0         16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No  Sun  Dinner     4              6.15   
..          ...   ...     ...    ...  ...     ...   ...               ...   
238       35.83  4.67  Female     No  Sat  Dinner     3             11.94   
239       29.03  5.92    Male     No  Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes  Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes  Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No  Sat  Dinner     2              8.91   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
238      Kimberly Crane      676184013727    Sat9777  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  

[163 rows x 11 columns]

In [73]:
df = pd.read_csv(r'C:\Users\Home\PycharmProjects\UDEMY_ML_NEW\data\movie_scores.csv')

In [75]:
df.isnull()

first_name  last_name    age    sex  pre_movie_score  post_movie_score
0       False      False  False  False            False             False
1        True       True   True   True             True              True
2       False      False  False  False             True              True
3       False      False  False  False            False             False
4       False      False  False  False            False             False

In [78]:
df[df['pre_movie_score'].notnull()]

first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [81]:
df[(df['pre_movie_score'].isnull()) & (df['first_name'].notnull())]

first_name last_name   age sex  pre_movie_score  post_movie_score
2       Hugh   Jackman  51.0   m              NaN               NaN

In [92]:
df.dropna(axis=1,thresh=4)

first_name last_name   age  sex
0        Tom     Hanks  63.0    m
1        NaN       NaN   NaN  NaN
2       Hugh   Jackman  51.0    m
3      Oprah   Winfrey  66.0    f
4       Emma     Stone  31.0    f

In [105]:
df.dropna(subset=['last_name', 'age'])

first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [107]:
df.fillna('NEW')

first_name last_name   age  sex pre_movie_score post_movie_score
0        Tom     Hanks  63.0    m             8.0             10.0
1        NEW       NEW   NEW  NEW             NEW              NEW
2       Hugh   Jackman  51.0    m             NEW              NEW
3      Oprah   Winfrey  66.0    f             6.0              8.0
4       Emma     Stone  31.0    f             7.0              9.0

In [114]:
df['pre_movie_score'].fillna(df['pre_movie_score'].mean())

0    8.0
1    7.0
2    7.0
3    6.0
4    7.0
Name: pre_movie_score, dtype: float64

In [116]:
df['pre_movie_score'].interpolate()

0    8.000000
1    7.333333
2    6.666667
3    6.000000
4    7.000000
Name: pre_movie_score, dtype: float64